// import type { Metadata } from "next";


// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <body>
//             {children}
//         </body>
//     );
// }
import React from 'react'

const page = () => {
  return (
    <div>
      
    </div>
  )
}

export default page
